version: 2
jobs:
  build-and-test:
    macos:
      xcode: "16.0.0"
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: xcodebuild build test -project 'CharcoalDemo/CharcoalDemo.xcodeproj' -scheme 'CharcoalDemo' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.0' -scmProvider system | xcpretty

  swiftlint:
    docker:
      - image: dantoml/swiftlint:latest
    steps:
      - checkout
      - run: swiftlint lint

workflows:
  version: 2
  build-and-test:
    jobs:
      - swiftlint
      - build-and-test
