version: 2
jobs:
  build-and-test:
    macos:
      xcode: "10.2.0"
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: xcodebuild -project Charcoal.xcodeproj -scheme "Demo" -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=12.2,name=iPhone X' build test | xcpretty

  swiftlint:
    docker:
      - image: dantoml/swiftlint:latest
    steps:
      - checkout
      - run: swiftlint lint

workflows:
  version: 2
  build-and-test:
    jobs:
      - swiftlint
      - build-and-test
