version: 2
jobs:
  build-and-test:
    macos:
      xcode: "12.2.0"
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: xcodebuild build test -workspace 'CharcoalDemo.xcworkspace' -scheme 'CharcoalDemo' -sdk iphonesimulator14.2 -destination 'platform=iOS Simulator,name=iPhone 8,OS=14.2' -scmProvider system | xcpretty

  swiftlint:
    docker:
      - image: dantoml/swiftlint:latest
    steps:
      - checkout
      - run: swiftlint lint

workflows:
  version: 2
  build-and-test:
    jobs:
      - swiftlint
      - build-and-test
