// Generated by generate_image_assets_symbols as a "Run Script" Build Phase
// WARNING: This file is autogenerated, do not modify by hand

import UIKit

extension UIImage {
    convenience init(named imageAsset: ImageAsset) {
        self.init(named: imageAsset.rawValue)!
    }
}

enum ImageAsset: String {
    case arrowDown
    case popoverArrow
}
